### ISSUE TITLE
Server ?

### ISSUE THREAD

**Issue by freedomtrain** [kewitz/dat-medium#1]
Is the code is the repository the server ?
Where is dat-medium.js located ?

Thanks

**Comment by kewitz** [comment]
I'm currently manually updating the dat and syncing with my Hashbase.io account:
dat://dat-medium-kewitz.hashbase.io/
I'll be creating a decent DNS for this in the future.

**Comment by freedomtrain** [comment]
How can I run the server ?

**Comment by kewitz** [comment]
@fredhampton this runs inside [Beaker](https://beakerbrowser.com/), which is a peer-to-peer browser with tools to create and host websites.
So, in practice you just need to run Beaker on your computer, fork a copy of this website for you and start editing the markdown files.

In short:
1. Get Beaker.
2. Access dat://474b40995a22d1c89230c71d4b9e23c5dfc75ac78968f2f8f0030d494713d11b/?page=fork
3. Start editing the website you created.
4. The website is being hosted by your browser as long as you're on-line.
     * You can also create an account in https://hashbase.io/, they seed 100mb for free.

**Comment by freedomtrain** [comment]
Ok...I understand !!! Vey cool..
What are the files in the repo ?

**Comment by kewitz** [comment]
@fredhampton they're the source-code for the app. They're also compiled and served through Dat.
