### ISSUE TITLE
"Invalid attempt to destructure non-iterable instance" when trying to fork

### ISSUE THREAD

**Issue by lachenmayer** [kewitz/dat-medium#9]
Hey there, awesome project! :) Was trying to give it a spin, but it didn't work unfortunately...

To reproduce:

1. Go to dat://474b40995a22d1c89230c71d4b9e23c5dfc75ac78968f2f8f0030d494713d11b/ in Beaker
2. Click on the 'fork' button in the top-right corner
3. Enter some stuff in the text fields & click create

Expected: Fork dialog opens
Actual: Nothing happens, the following error is shown in the dev console:

![image](https://user-images.githubusercontent.com/38614/33961328-9178d7fa-e045-11e7-94ba-60ef0042c68e.png)

```
Uncaught TypeError: Invalid attempt to destructure non-iterable instance
    at dat-medium.js:formatted:24678
    at HTMLFormElement.i (dat-medium.js:formatted:24703)
```

Versions:
dat-medium dat://474b40995a22d1c89230c71d4b9e23c5dfc75ac78968f2f8f0030d494713d11b+33/
Beaker Browser v0.7.10
Mac OS 10.12.6

**Comment by kewitz** [comment]
Thanks @lachenmayer, the bug was affecting when forking without a display picture.
I just merged a fix for that.

**Comment by lachenmayer** [comment]
Awesome, thank you! :)
